Program 2 : UnivariateStats
libname uni "/folders/myfolders/Datasets/Univariate Statistics";

/*** getting summary statistics for numeric variables using proc means ***/

proc means data=sashelp.class;
run;


proc means data=uni.whitewine;
var alcohol ph density;
run;


proc means data=uni.whitewine mean std;
run;



proc means data=uni.whitewine median q1 q3 cv;
var quality alcohol;
run;


/*above code gives 5 default numeric summaries 
for all numeric variables present in the data . Using var statement
and other stats option we can get non default summary for specific 
vars as well*/


/* to get group wise summary stats you can use by statement */
proc sort data=uni.cars;
by cyl;
run;

proc means data=uni.cars median p1;
var mpg;
by cyl;
run;


/* using class statement instead of by */

proc means data=sashelp.cars mean;
var msrp;
class drivetrain origin make;
run;











/* getting percentage of outliers through indicator variables */
/* we have taken some hypothetical upper lower limits for 
variables in consideration here */

data wine;
set uni.whitewine(keep=alcohol ph density);
a=(alcohol>12.3 or alcohol<8.55);
p=(ph>3.375 or ph<2.995);
d=(density>0.99829 or density<0.98953);
run;

proc means data=wine sum mean;
var a p d;
run;



/**** proc freq for summary of categorical variable ****/


proc freq data=uni.cars;
table cyl;
run;


/* this was an example single variable freq count summary */
/* you can ignore various percentages and cumulative percentages
generated by default */


proc freq data=uni.cars;
table cyl/ nocum;
run;

proc freq data=uni.cars;
table cyl/ nopercent;
run;

proc freq data=uni.cars ;
table cyl/ nopercent nocum;
run;


/*cross table */


proc freq data=sashelp.cars;
table origin*drivetrain;
run;


/* norow nocol nofreq */
proc freq data=sashelp.cars;
table origin*drivetrain/ nocol nopercent ;
run;


/**** making box plot using sgplot ****/

proc sgplot data=uni.cars;
title "Verticle Box Plot for Miles Per Gallon";
vbox mpg ;
run;


proc sgplot data=uni.cars;
title "Horizontal Box Plot for Miles Per Gallon";
hbox mpg;
run;


/**** making histograms using sgplot ****/

PROC SGPLOT DATA = uni.cars;
title "Distribution of Miles Per Gallon";
histogram mpg ; 
run;


PROC SGPLOT DATA = uni.cars;
title "Distribution of Miles Per Gallon";
 histogram mpg ;
 density mpg;
run;

/*--Comparative Scatter Plot--*/

title 'Mileage by Horsepower and Weight';
proc sgscatter data=sashelp.cars(where=(type in ('Sedan' 'Sports')));
  label mpg_city='City';
  label mpg_highway='Highway';
  compare x=(mpg_city mpg_highway) y=(horsepower weight) /
     transparency=0.8 markerattrs=graphdata1(symbol=circlefilled);
  run;

/*--Scatter Plot Matrix--*/

title 'Vehicle Profile';
proc sgscatter data=sashelp.cars(where=(type in ('Sedan' 'Sports')));
  label mpg_city='City';
  label mpg_highway='Highway';
  matrix mpg_city mpg_highway horsepower weight /
     transparency=0.8 markerattrs=graphdata3(symbol=circlefilled);
  run;

/*--Bar Panel--*/

title 'Mileage by Origin and Type';
proc sgpanel data=sashelp.cars(where=(type in ('Sedan' 'Sports'))) noautolegend;
  panelby Type / novarname columns=2 onepanel;
  vbar origin / response=mpg_city stat=mean group=origin;
  rowaxis grid;
  run;

/*--Fit Plot--*/

title 'Mileage by Horsepower for USA';
proc sgplot data=sashelp.cars(where=(origin='USA'));
  reg x=horsepower y=mpg_city / degree=2 clm='CL Mean';
  keylegend / location=inside position=topright across=1;
  xaxis grid;
  yaxis grid;
  run;


